menu:
    name: "Race Selection"
    slots: 45 # Has to be a multiple of 9
    glass-filled: false
settings:
    autosave: 6000
    require-race: true # Controls if a player can be raceless
    default-race: Human
    set-default-race-first-join: true
    allow-player-race-changes: true # Allow players to change their race on their own
    race-change-cost: 25000
    race-change-cost-type: money # Can be money or exp
    race-unlocks: true
    race-unlock-uses-cost: false # If true, a player must have the value set above to change races
    give-items-on-race-change: true # Sets if the player get the race items when they change races
    allow-reclaiming-items: true
    reclaim-items-cost: 5000
    allow-reclaiming-skillpoints: true
    reclaim-skillpoint-cost: 5000
    send-skillpoint-message-on-join: true
    use-projectile-event: false
    projectile-launchers: [bow, snowball, egg, trident, splash_potion, thrown_exp_bottle]
    projectile-types: [arrow, egg, snowball, trident, fireball, small_fireball, splash_potion, thrown_exp_bottle]
    disabled-worlds: [disabledworld1, disabledworld2]
